name: deploy
on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: fogpipe/cloud-actions/auth@v1
        with:
          service-account: a14028e4-c833-416d-a82b-f05d798ae426

      - run: curl -fsSL https://raw.githubusercontent.com/fogpipe/cloud-cli/main/install.sh | sh

      - run: fpcloud website deploy website web --org rkv --project website
